- .eslintrc.js
- src/app/app.ts
- src/app/modules.ts
- src/app/modules/audio/endpoint.ts
- src/app/modules/audio/method.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/stores/audioAccount.ts
- src/app/modules/audio/types.ts
- src/commands/genesis-block/create.ts
- src/commands/start.ts
- src/commands/transaction/create.ts
- src/commands/transaction/sign.ts
- test/unit/modules/audio/module.spec.ts
This PR resolves #8
Generated the substore using Lisk Commander. Then Adjusted to match the required schemas.
> Implement the account substore for the audio module - Closes #8

- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/stores/audio.ts
- src/app/modules/audio/stores/audioAccount.ts
- src/app/modules/audio/types.ts
- test/unit/modules/audio/module.spec.ts
This PR resolves #7
Created the substore. Also fixed some eslint issues.
> Implement the Audio Substore for the Audio module -Closes #7

- src/app/modules/audio/endpoint.ts
- src/app/modules/audio/types.ts
This PR resolves #21
- Added the getAudio endpoint according to the specifications
> Create getAudio endpoint of the audio module - Closes #21

- src/app/modules/audio/commands/destroy_command.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- test/unit/modules/audio/commands/destroy_command.spec.ts
This PR resolves #11
Implemented as explained in the ticket
> Implement the Destroy command for the Audio module - Closes #11

- src/app/modules/audio/commands/transfer_command.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- test/unit/modules/audio/commands/transfer_command.spec.ts
This PR resolves #13
Implemented as described in the ticket.
> Implement the Transfer command for the Audio module - Closes #13

- src/app/modules/audio/commands/set_attribute_command.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- test/unit/modules/audio/commands/set_attribute_command.spec.ts
This PR resolves #12
Created the setAttribute command and tested with several audio NFTs
> Implement the SetAttributes command for the Audio module - Closes #12

- src/app/modules.ts
- src/app/modules/collection/endpoint.ts
- src/app/modules/collection/method.ts
- src/app/modules/collection/module.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/stores/collection.ts
- src/app/modules/collection/stores/collectionAccount.ts
- src/app/modules/collection/types.ts
- test/unit/modules/collection/module.spec.ts
This PR resolves #29
Work in progress
> Implement the Collection Substore for the Collection module - Closes #29

- src/app/modules/collection/commands/create_command.ts
- src/app/modules/collection/constants.ts
- src/app/modules/collection/module.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
- src/app/modules/collection/utils.ts
- test/unit/modules/collection/commands/create_command.spec.ts
- test/unit/modules/collection/module.spec.ts
This PR resolves #30
- Add missing `type` property to the collection.
- Implement the `create` command
> Implement the Create command for the Collection module - Closes #30

- src/app/modules/audio/commands/destroy_command.ts
- src/app/modules/collection/commands/destroy_command.ts
- src/app/modules/collection/module.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
- test/unit/modules/collection/commands/destroy_command.spec.ts
This PR resolves #31
Create the command as explained in the ticket
> Implement the Destroy command for the Collection module - Closes #31

- src/app/modules/audio/commands/transfer_command.ts
- src/app/modules/collection/commands/transfer_command.ts
- src/app/modules/collection/module.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
- test/unit/modules/collection/commands/create_command.spec.ts
- test/unit/modules/collection/commands/destroy_command.spec.ts
- test/unit/modules/collection/commands/transfer_command.spec.ts
This PR resolves #33
- Removed redundant validations from the transfer command of the audio module
- Implement the transfer command for the collection module according to the ticket
> Implement the Transfer command for the Collection module - Closes #33

- src/app/modules/audio/commands/set_attributes_command.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- src/app/modules/collection/commands/set_attributes_command.ts
- src/app/modules/collection/module.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
- test/unit/modules/audio/commands/__snapshots__/set_attributes_command.spec.ts.snap
- test/unit/modules/audio/commands/set_attributes_command.spec.ts
- test/unit/modules/collection/commands/__snapshots__/create_command.spec.ts.snap
- test/unit/modules/collection/commands/__snapshots__/destroy_command.spec.ts.snap
- test/unit/modules/collection/commands/__snapshots__/set_attributes_command.spec.ts.snap
- test/unit/modules/collection/commands/__snapshots__/transfer_command.spec.ts.snap
- test/unit/modules/collection/commands/set_attributes_command.spec.ts
This PR resolves #32
- Renamed the `SetAttribute` command of the audio module to `SetAttributes`. (made the word plural)
- Add the `SetAttribute` command for the collection module as explained by then ticket.
> Implement the SetAttributes command for the Collection module - Closes #32

- src/app/modules/collection/endpoint.ts
> Create getCollection endpoint of the collection module - Closes #41

- src/app/modules/audio/controllers.ts
- src/app/modules/audio/endpoint.ts
- src/app/modules/audio/method.ts
- src/app/modules/audio/types.ts
This PR resolves #45
- Implement the Store type, since I couldn't find such type exported from the Lisk SDK
- Moved the retrieval logic from the endpoint class to controllers
- Used the controllers to implement the methods of the Audio module.
> Implement the methods of the Audio module - Closes #45

- src/app/modules/audio/controllers.ts
- src/app/modules/audio/endpoint.ts
- src/app/modules/audio/method.ts
- src/app/modules/collection/controllers.ts
- src/app/modules/collection/endpoint.ts
- src/app/modules/collection/method.ts
- src/app/modules/collection/types.ts
This PR resolves #46 
- Implement the Store type, since I couldn't find such type exported from the Lisk SDK
- Moved the retrieval logic from the endpoint class to controllers
- Used the controllers to implement the methods of the Collection module.
> Implement the methods of the Collection module - Closes #46

- src/app/modules/audio/commands/create_command.ts
- src/app/modules/audio/commands/destroy_command.ts
- src/app/modules/audio/commands/set_attributes_command.ts
- src/app/modules/audio/commands/transfer_command.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- src/app/modules/collection/commands/create_command.ts
- src/app/modules/collection/commands/destroy_command.ts
- src/app/modules/collection/commands/set_attributes_command.ts
- src/app/modules/collection/commands/transfer_command.ts
- src/app/modules/collection/method.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
This PR resolves #62, #63, #64, #65
> Update Audio module to account for loyalty rights - Closes #62, Closes #63, Closes #64, Closes #65

- src/app/modules.ts
- src/app/modules/subscription/endpoint.ts
- src/app/modules/subscription/method.ts
- src/app/modules/subscription/module.ts
- src/app/modules/subscription/schemas.ts
- src/app/modules/subscription/stores/collection.ts
- src/app/modules/subscription/types.ts
- test/unit/modules/subscription/module.spec.ts
This PR resolves #57
Implemented the subscription substore according the define schema
> Implement the Subscription Substore for the Subscription module - Closes #57

- src/app/modules/subscription/commands/create_command.ts
- src/app/modules/subscription/commands/purchase_command.ts
- src/app/modules/subscription/constants.ts
- src/app/modules/subscription/module.ts
- src/app/modules/subscription/schemas.ts
- src/app/modules/subscription/types.ts
- test/unit/modules/audio/commands/__snapshots__/create_command.spec.ts.snap
- test/unit/modules/audio/commands/__snapshots__/transfer_command.spec.ts.snap
- test/unit/modules/subscription/commands/__snapshots__/create_command.spec.ts.snap
- test/unit/modules/subscription/commands/__snapshots__/purchase_command.spec.ts.snap
- test/unit/modules/subscription/commands/create_command.spec.ts
This PR resolves #54
Added CREATE command as follows:
- Create subscription ID
- Create subscription object
- Store development account since it's the owner
- Store the subscription object in the blockchain
> Implement the Create command for the Subscription module - Closes #54

- src/app/modules/subscription/commands/create_command.ts
- src/app/modules/subscription/controllers.ts
- src/app/modules/subscription/endpoint.ts
- src/app/modules/subscription/method.ts
- src/app/modules/subscription/schemas.ts
- src/app/modules/subscription/types.ts
This PR resolves #72 , #71 
- Fixed issue with the schemas of the CREATE command
- Add controllers for `getAccount` and `getSubscription`
- Use controllers to create methods and endpoints
> Create endpoints and methods of the subscription module - Closes #72, Closes #71

- src/app/modules/subscription/commands/update_members_command.ts
- src/app/modules/subscription/module.ts
- src/app/modules/subscription/schemas.ts
- src/app/modules/subscription/types.ts
- test/unit/modules/subscription/commands/update_members_command.spec.ts
This PR resolves #61
Add updateMembers command as follows
- Validate against the maxMembers
- Validate against owner of subscription 
- Added ID to newly added members
- Remove ID from eliminated members
- Update members of the subscription NFT
> Implement the updateMembers command for the Subscription module - Closes #61

- src/app/modules/subscription/controllers.ts
- src/app/modules/subscription/endpoint.ts
- src/app/modules/subscription/method.ts
- src/app/modules/subscription/types.ts
This PR resolves #77
Added hasSubscription to the methods and endpoints of the subscription module.
> Add hasSubscription endpoint - Closes #77

- src/app/modules.ts
- src/app/modules/audio/commands/reclaim_command.ts
- src/app/modules/audio/module.ts
- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- test/unit/modules/audio/commands/__snapshots__/create_command.spec.ts.snap
- test/unit/modules/audio/commands/__snapshots__/reclaim_command.spec.ts.snap
- test/unit/modules/audio/commands/__snapshots__/stream_command.spec.ts.snap
- test/unit/modules/audio/commands/reclaim_command.spec.ts
- test/unit/modules/subscription/commands/__snapshots__/update_members_command.spec.ts.snap
This PR resolves #60
- Collect list of audios
- Aggregate the total income
- Transfer to tokens from treasury to the sender
- Reset the audios
> Implement the reclaim command for the Subscription module - Closes #60

- src/app/modules/audio/commands/create_command.ts
- src/app/modules/audio/commands/set_attributes_command.ts
- src/app/modules/audio/constants.ts
- src/app/modules/audio/controllers/query.ts
- src/app/modules/audio/endpoint.ts
- src/app/modules/audio/method.ts
- src/app/modules/audio/types.ts
- src/app/modules/audio/utils.ts
This PR resolves #82
Updated values according to Web Player
> Update valid genres to match web-player requirements

- src/app/app.ts
- src/app/modules.ts
- src/app/modules/audio/commands/reclaim_command.ts
- src/app/modules/audio/commands/stream_command.ts
- src/app/modules/subscription/commands/purchase_command.ts
This PR resolves #93
Fixed as explained in the ticket
> Fix transfer issue with the subscription purchase command 

- src/app/modules.ts
- src/app/modules/user/endpoint.ts
- src/app/modules/user/method.ts
- src/app/modules/user/module.ts
- src/app/modules/user/schemas.ts
- src/app/modules/user/stores/user.ts
- src/app/modules/user/stores/userAccount.ts
- src/app/modules/user/types.ts
- test/unit/modules/user/module.spec.ts
This PR resolves #96 
- Created the User store
- Created the User Account store
- Create corresponding types and schemas
- Registered the stores in the module
> Create the basis of the user module

- src/app/modules/user/controllers/query.ts
- src/app/modules/user/endpoint.ts
- src/app/modules/user/method.ts
- src/app/modules/user/schemas.ts
- src/app/modules/user/types.ts
- test/unit/modules/user/commands/__snapshots__/create_command.spec.ts.snap
This PR resolves #104
- Created the `getAccount` endpoint
- Created the `getAccount` method
- Renamed `socialAccounts.type` to `socialAccounts.platform`
> Create getAccount endpoint of the user module

- src/app/modules/user/controllers/query.ts
- src/app/modules/user/endpoint.ts
- src/app/modules/user/method.ts
This PR resolves #103
- Create getUser endpoint
> Add getUser endpoint

- src/app/modules/audio/schemas.ts
- src/app/modules/audio/types.ts
- src/app/modules/collection/schemas.ts
- src/app/modules/collection/types.ts
- src/app/modules/profile/schemas.ts
- src/app/modules/subscription/schemas.ts
- src/app/schemas.ts
> Remove artistName from Audio and Collection 

- src/app/modules/audio/schemas.ts
- src/app/modules/collection/types.ts
- src/app/utils.ts
- test/unit/modules/audio/commands/__snapshots__/create_command.spec.ts.snap
This PR resolves #119
- Used md5 hash of the tx params to calculate the content.
> Use content hash to calculate the ID

- package-lock.json
- package.json
> Bump version 0.3.0

- src/app/modules/anchor/commands/vote_command.ts
> Creator Cannot Vote for Own Anchor
